pfetch
#cose
export ZSH="$HOME/.oh-my-zsh"

#Theme
ZSH_THEME="gallifrey"
source $ZSH/oh-my-zsh.sh

#plugins
plugins=(git)


#Aliases
alias open=xdg-open
alias zshconf="nano ~/.zshrc"
alias alaconf="nano ~/.config/alacritty/alacritty.yml"
alias roficonf="nano ~/.config/rofi/launchers/text/launcher.sh"
alias chrome="google-chrome-stable"